Region: '{AWS_REGION}'
Image:
  CustomAmi: '{WRF_AMI}'
  Os: alinux2
SharedStorage:
  - Name: myebs
    StorageType: Ebs
    MountDir: /shared
    EbsSettings:
      VolumeType: gp2
      Size: 20
  - Name: myfsx
    StorageType: FsxLustre
    MountDir: /fsx
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: SCRATCH_2
HeadNode:
  InstanceType: c6a.xlarge
  Networking:
    SubnetId: '{SUBNET_ID}'
  Ssh:
    KeyName: '{SSH_KEY_NAME}'
  LocalStorage:
    RootVolume:
      Size: 40
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: hpc6a48xlarge
      ComputeResources:
        - Name: hpc6a48xlarge
          InstanceType: hpc6a.48xlarge
          MinCount: 0
          MaxCount: 64
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - '{SUBNET_ID}'
        PlacementGroup:
          Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 40
