Region: '{AWS_REGION}'
Image:
  CustomAmi: '{OPENFOAM_AMI}'
  Os: alinux2
SharedStorage:
  - Name: myebs
    StorageType: Ebs
    MountDir: /shared
    EbsSettings:
      VolumeType: gp2
      Size: 20
  - Name: myfsx
    StorageType: FsxLustre
    MountDir: /fsx
    FsxLustreSettings:
      StorageCapacity: 1200
      DeploymentType: SCRATCH_2
HeadNode:
  InstanceType: g4dn.xlarge
  Networking:
    SubnetId: '{SUBNET_ID}'
  Ssh:
    KeyName: '{SSH_KEY_NAME}'
  Dcv:
    Enabled: true
  LocalStorage:
    RootVolume:
      Size: 40
  Iam:
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      - Policy: arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue0
      ComputeResources:
        - Name: hpc6a
          InstanceType: hpc6a.48xlarge
          MinCount: 0
          MaxCount: 64
          DisableSimultaneousMultithreading: true
          Efa:
            Enabled: true
      Iam:
        AdditionalIamPolicies:
          - Policy: arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - Policy: arn:aws:iam::aws:policy/service-role/AmazonSSMMaintenanceWindowRole
      Networking:
        SubnetIds:
          - '{SUBNET_ID}'
        PlacementGroup:
          Enabled: true
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 40
