# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-yaml
    -   id: detect-aws-credentials
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: trailing-whitespace
-  repo: https://github.com/pre-commit/mirrors-yapf
   rev: v0.30.0
   hooks:
   -    id: yapf
- repo: https://github.com/executablebooks/mdformat
  rev: 0.3.3  # Use the ref you want to point at
  hooks:
  - id: mdformat
    # optional
    additional_dependencies:
    - mdformat-tables
    - mdformat-black
    - mdformat-beautysh
- repo: https://github.com/lovesegfault/beautysh.git
  rev: v6.1.0
  hooks:
  - id: beautysh
