version: 0.2

env:
  shell: bash
  variables:
    PACKER_VERSION: "1.7.5"
    PACKER_VERSION_SHA256SUM: "a574d20719e86d9d38854050184b78d158e62619b2a4b33b79d03b94c782dbc5"
    COMPANY: "acme"
    AWS_REGION: "us-east-2"
    AWS_MAX_ATTEMPTS: 60
    AWS_POLL_DELAY_SECONDS: 60
  parameter-store:
    INTEL_SERIAL: INTEL_SERIAL_NUMBER

phases:
  pre_build:
    commands:
      - echo "Installing Packer"
      - curl -O https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
      - echo "${PACKER_VERSION_SHA256SUM}  packer_${PACKER_VERSION}_linux_amd64.zip" > checksum && sha256sum -c checksum
      - unzip packer_${PACKER_VERSION}_linux_amd64.zip
      - echo "Install session manager CLI"
      - curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/linux_64bit/session-manager-plugin.rpm" -o "session-manager-plugin.rpm"
      - yum install -y session-manager-plugin.rpm
      - echo "Validating Packer template ${OS_TYPE}"
      - cd amis/${OS_TYPE}-pc-gromacs
      - ../../packer validate -var-file variables.json -var company_name=${COMPANY} -var parallel_cluster_version=${PC_VERSION} ${OS_TYPE}-pc-gromacs.json
      - cd ../../
  build:
    commands:
      - cd amis/${OS_TYPE}-pc-gromacs
      - ../../packer build -color=false -var-file variables.json -var company_name=${COMPANY} -var parallel_cluster_version=${PC_VERSION} ${OS_TYPE}-pc-gromacs.json | tee build_${OS_TYPE}.log
      - cd ../../
  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" amis/${OS_TYPE}-pc-gromacs/build_${OS_TYPE}.log | cut -d' ' -f2 > ami_id_${OS_TYPE}.txt
      # Packer doesn't return non-zero status; we must do that if Packer build failed
      - test -s ami_id_${OS_TYPE}.txt || exit 1
      - echo "build completed on `date`"
artifacts:
  files:
    - amis/${OS_TYPE}-pc-gromacs/build_${OS_TYPE}.log
  discard-paths: yes
